name: build and push docker image

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: make gradle executable
        run: chmod +x ./gradlew

      - name: Get project version from Gradle
        id: get_version
        run: |
          VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')

      - name: build JAR with gradle
        run: ./gradlew check bootJar --no-daemon
        
      - name: build docker image
        run: |
            docker build -t my-photo-manager:latest .

      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            8u363/my-photo-manager:${{ steps.get_version.outputs.version }}
            8u363/my-photo-manager:latest